Repository Tangerine-Community/Tangerine, pull requests merged in 2018-03, with the labels that each got.

#657 Add update runner module to shell / Schema updates for beta9
  client/shell/src/app/app.module.ts
  client/shell/src/app/core/auth/_services/user.service.ts
  client/shell/src/app/core/update/update-routing.module.ts
  client/shell/src/app/core/update/update.module.ts
  client/shell/src/app/core/update/update/update.component.css
  client/shell/src/app/core/update/update/update.component.html
  client/shell/src/app/core/update/update/update.component.spec.ts
  client/shell/src/app/core/update/update/update.component.ts
  client/shell/src/app/core/update/update/updates.ts
Labels: in progress, v3.x.x

#658 V3 casemagement rework
  client/shell/src/app/app.component.html
  client/shell/src/app/app.component.ts
  client/shell/src/app/case-management/_services/case-management.service.ts
  client/shell/src/app/case-management/case-details/case-details.component.css
  client/shell/src/app/case-management/case-details/case-details.component.html
  client/shell/src/app/case-management/case-details/case-details.component.spec.ts
  client/shell/src/app/case-management/case-details/case-details.component.ts
  client/shell/src/app/case-management/case-management-routing.module.ts
  client/shell/src/app/case-management/case-management.component.css
  client/shell/src/app/case-management/case-management.component.html
  client/shell/src/app/case-management/case-management.component.spec.ts
  client/shell/src/app/case-management/case-management.component.ts
  client/shell/src/app/case-management/case-management.module.ts
  client/shell/src/app/case-management/form-list/form-list.component.html
  client/shell/src/app/case-management/form-list/form-list.component.ts
  client/shell/src/app/case-management/form-responses-list/form-responses-list.component.html
  client/shell/src/app/case-management/form-responses-list/form-responses-list.component.spec.ts
  client/shell/src/app/case-management/form-responses-list/form-responses-list.component.ts
  client/shell/src/app/case-management/schools-visited/schools-visited.component.css
  client/shell/src/app/case-management/schools-visited/schools-visited.component.html
  client/shell/src/app/case-management/schools-visited/schools-visited.component.spec.ts
  client/shell/src/app/case-management/schools-visited/schools-visited.component.ts
  client/shell/src/app/core/auth/auth-routing.module.ts
  client/shell/src/app/core/auth/auth.module.ts
  client/shell/src/app/core/auth/login-remote-server/login-remote-server.component.html
  client/shell/src/app/core/auth/login-remote-server/login-remote-server.component.spec.ts
  client/shell/src/app/core/auth/login-remote-server/login-remote-server.component.ts
  client/shell/src/app/core/auth/register-remote-server/register-remote-server.component.css
  client/shell/src/app/core/auth/register-remote-server/register-remote-server.component.html
  client/shell/src/app/core/auth/register-remote-server/register-remote-server.component.spec.ts
  client/shell/src/app/core/auth/register-remote-server/register-remote-server.component.ts
  client/shell/src/app/core/auth/registration/registration.component.html
  client/shell/src/app/core/auth/registration/registration.component.ts
  client/shell/src/app/shared/_components/redirect-to-default-route/redirect-to-default-route.component.ts
  client/shell/src/app/shared/_components/tangy-tooltip/tangy-tooltip.component.css
  client/shell/src/app/shared/_components/tangy-tooltip/tangy-tooltip.component.html
  client/shell/src/app/shared/_components/tangy-tooltip/tangy-tooltip.component.ts
  client/shell/src/app/shared/shared.module.ts
  client/shell/src/app/tangy-forms/tangy-form-service.js
  client/shell/src/app/tangy-forms/tangy-forms-player/tangy-forms-player.component.ts
  client/shell/src/app/user-profile/create-profile-guard.service.ts
  client/shell/src/app/user-profile/user-profile.component.ts
Labels: in progress, v3.x.x

#688 V3 casemagement rework
  client/shell/src/app/case-management/all-observations/all-observations.component.css
  client/shell/src/app/case-management/all-observations/all-observations.component.html
  client/shell/src/app/case-management/all-observations/all-observations.component.spec.ts
  client/shell/src/app/case-management/all-observations/all-observations.component.ts
Labels: in progress

#700 Add window.fillUp for testing disk usage
  client/tangy-forms/src/tangy-form/cat.js
Labels: review, technical, v3.x.x

#705 V3 use compression on sync
  client/shell/package.json
  client/shell/src/app/core/sync-records/_services/syncing.service.ts
  server/index.js
  server/package.json
Labels: in progress, v3.x.x

#716 Add tangy-select element and select lists field demo
  client/content/default/field-demo/form.html
  client/content/default/field-demo/select-lists.html
  client/tangy-forms/src/tangy-form/tangy-form.js
  client/tangy-forms/src/tangy-select/mdc-select-style.js
  client/tangy-forms/src/tangy-select/tangy-select.js
Labels: in progress, v3.x.x

#720 Allow Arabic characters in regex
  editor/src/js/modules/subtest/prototypes/LocationEditView.coffee
Labels: in progress

#704 Observations by Location Component
  client/shell/src/app/case-management/_services/case-management.service.ts
  client/shell/src/app/case-management/all-observations/all-observations.component.ts
  client/shell/src/app/case-management/case-details/case-details.component.html
  client/shell/src/app/case-management/case-management.module.ts
  client/shell/src/app/case-management/observations-by-location/observations-by-location.component.css
  client/shell/src/app/case-management/observations-by-location/observations-by-location.component.html
  client/shell/src/app/case-management/observations-by-location/observations-by-location.component.spec.ts
  client/shell/src/app/case-management/observations-by-location/observations-by-location.component.ts
Labels: in progress

#706 Remove tangy-form.on-change from form responses
  client/tangy-forms/src/tangy-form/tangy-form.js
Labels: in progress, v3.x.x

#722 V3 gps rework
  client/shell/src/app/app.component.ts
  client/shell/src/app/case-management/_services/case-management.service.ts
  client/shell/src/app/case-management/case-details/case-details.component.html
  client/tangy-forms/src/tangy-gps/tangy-gps.js
Labels: in progress

#737 V2.x.x—arabic RTL support
  client/src/css/tangerine-rtl.css
  client/src/css/tangerine.less-rtl.css
  client/src/js/boot.coffee
  client/src/js/modules/navigation/NavigationView.coffee
  client/src/js/modules/subtest/prototypes/LocationEditView.coffee
  client/src/js/modules/user/LoginView.coffee
  client/src/locales/ar.coffee
Labels: in progress

#731 Cleaned up the services, added ability for assessor to upload other u…
  client/shell/src/app/app.component.ts
  client/shell/src/app/core/auth/_services/user.service.ts
  client/shell/src/app/core/sync-records/_services/syncing.service.ts
  client/shell/src/app/core/sync-records/sync-records.module.ts
  client/shell/src/app/core/sync-records/sync-records/sync-records.component.html
  client/shell/src/app/core/sync-records/sync-records/sync-records.component.ts
  client/shell/src/app/core/update/update/update.component.ts
  client/shell/src/app/tangy-forms/tangy-form-service.js
Labels: in progress

#739 V3 export client data json
  client/shell/src/app/app.component.html
  client/shell/src/app/app.module.ts
  client/shell/src/app/core/auth/_services/user.service.ts
  client/shell/src/app/core/export-data/export-data-routing.module.ts
  client/shell/src/app/core/export-data/export-data.module.ts
  client/shell/src/app/core/export-data/export-data/export-data.component.css
  client/shell/src/app/core/export-data/export-data/export-data.component.html
  client/shell/src/app/core/export-data/export-data/export-data.component.spec.ts
  client/shell/src/app/core/export-data/export-data/export-data.component.ts
  client/shell/src/app/core/sync-records/_services/syncing.service.ts
  client/shell/src/app/core/sync-records/sync-records/sync-records.component.ts
  client/shell/src/app/core/update/update/update.component.ts
Labels: in progress

#741 V3 recover password
  client/shell/src/app/app-routing.module.ts
  client/shell/src/app/core/auth/_guards/upload-guard.service.spec.ts
  client/shell/src/app/core/auth/_guards/upload-guard.service.ts
  client/shell/src/app/core/auth/_services/authentication.service.ts
  client/shell/src/app/core/auth/_services/user.model.interface.ts
  client/shell/src/app/core/auth/_services/user.service.ts
  client/shell/src/app/core/auth/auth-routing.module.ts
  client/shell/src/app/core/auth/login/login.component.html
  client/shell/src/app/core/auth/login/login.component.ts
  client/shell/src/app/core/auth/registration/registration.component.html
  client/shell/src/app/core/auth/registration/registration.component.ts
  client/shell/src/app/core/export-data/export-data/export-data.component.ts
  client/shell/src/app/core/sync-records/_services/syncing.service.ts
  client/shell/src/app/core/sync-records/sync-records.module.ts
Labels: review

#743 Upload user profiles on sync. makes references to #723
  client/shell/src/app/tangy-forms/tangy-form-service.js
Labels: in progress
