Repository Tangerine-Community/Tangerine, pull requests merged in 2018-04, with the labels that each got.

#769 V3 export client data 346
  client/shell/src/app/app.component.ts
  client/shell/src/app/core/export-data/export-data/export-data.component.ts
  client/shell/src/typings.d.ts
Labels: in progress

#789 V3 integrate couchdb
  config.defaults.sh
  develop.sh
  server/index.js
  server/package-lock.json
  server/package.json
  start.sh
Labels: in progress, v3.x.x

#770 Get e2e tests on the rails for v3
  .travis.yml
  client/shell/e2e/app.e2e-spec.ts
  client/shell/e2e/app.po.ts
  client/shell/src/app/core/auth/login/login.component.html
Labels: in progress, v3.x.x

#820 PR for #794: Remove the user manual link on support page that was specific to v2
  editor/src/app/support/support.component.html
Labels: in progress, v3.x.x

#839 Prevent having to scroll up in editor after clicking a link deep in page
  editor/src/app/groups/group/group.component.ts
  editor/src/app/groups/new-group/new-group.component.ts
Labels: in progress, v3.x.x

#815 V3 edit form.html, app-config.json, location-list.json, and translations.json
  client/content/default/reports/form.html
  client/tangy-forms/bower.json
  client/tangy-forms/editor.html
  client/tangy-forms/src/tangy-editor-app/tangy-editor-app.js
  client/tangy-forms/src/tangy-editor-app/tangy-editor-file-editor.js
  client/tangy-forms/src/tangy-editor-app/tangy-editor-file-list.js
  server/index.js
  server/package.json
Labels: review

#840 V3 dev
  client/content/default/reports/form.html
  client/tangy-forms/bower.json
  client/tangy-forms/editor.html
  client/tangy-forms/src/tangy-editor-app/tangy-editor-app.js
  client/tangy-forms/src/tangy-editor-app/tangy-editor-file-editor.js
  client/tangy-forms/src/tangy-editor-app/tangy-editor-file-list.js
  server/index.js
  server/package.json
Labels: in progress

#819 PR for #795: Remove home page used on hub and other cruft
  editor/src/app/app-routing.module.ts
  editor/src/app/app.component.html
  editor/src/app/app.module.ts
  editor/src/app/billing/billing-routing.module.ts
  editor/src/app/billing/billing.component.ts
  editor/src/app/billing/billing.html
  editor/src/app/billing/billing.module.ts
  editor/src/app/billing/services/billing.service.ts
  editor/src/app/groups/groups-routing.module.ts
  editor/src/app/home/_directives/alert.component.html
  editor/src/app/home/_directives/alert.component.js
  editor/src/app/home/_directives/alert.component.js.map
  editor/src/app/home/_directives/alert.component.ts
  editor/src/app/home/_directives/index.js
  editor/src/app/home/_directives/index.js.map
  editor/src/app/home/_directives/index.ts
  editor/src/app/home/home-routing.module.ts
  editor/src/app/home/home.component.css
  editor/src/app/home/home.component.html
  editor/src/app/home/home.component.spec.ts
  editor/src/app/home/home.component.ts
  editor/src/app/home/home.module.ts
  editor/src/app/home/home.service.ts
  editor/src/app/registration/checkout.component.html
  editor/src/app/registration/checkout.component.ts
  editor/src/app/registration/login-form.component.html
  editor/src/app/registration/plan.component.html
  editor/src/app/registration/plan.component.ts
  editor/src/app/registration/registration-routing.module.ts
  editor/src/app/registration/registration.module.ts
  editor/src/app/registration/services/paypal.service.ts
Labels: area:editor, review, v3.x.x
