Repository Tangerine-Community/Tangerine, pull requests merged in 2018-05, with the labels that each got.

#850 V2 reporting service
  Dockerfile
  build-and-run.sh
  client/package.json
  develop.sh
  ecosystem.json
  editor/result/.couchappignore
  editor/result/.couchapprc
  editor/result/_id
  editor/result/views/byParentId/map.coffee
  editor/result/views/byParentId/map.js
  editor/result/views/byTripId/map.coffee
  editor/result/views/byTripId/map.js
  editor/src/js/modules/result/ResultsView.coffee
  editor/src/js/modules/workflow/WorkflowMenuView.coffee
  entrypoint.sh
  reporting/LICENSE.txt
  reporting/README.md
  reporting/config.js
  reporting/controllers/assessment.js
  reporting/controllers/changes.js
  reporting/controllers/generate_csv.js
  reporting/controllers/result.js
  reporting/controllers/trip.js
  reporting/controllers/workflow.js
  reporting/index.js
  reporting/package.json
  reporting/public/index.html
  reporting/public/style.css
  reporting/public/tangerine_logo.png
  reporting/start.sh
  reporting/utils/dbQuery.js
  server/Group.js
  server/index.js
  server/notifyReportingServer.js
  server/routes/group/new-group.js
  start.sh
  tangerine-nginx.template
  tangerine.conf
Labels: in progress

#651 PR: Performance improvements for v3 Editor
  Dockerfile
  develop.sh
  editor/package.json
  editor/src/app/auth-guard.service.ts
  editor/src/app/auth.service.ts
  editor/src/main.ts
  editor/workbox-cli-config.js
  entrypoint-development.sh
Labels: in progress

#846 Group and db listening
  client/tangy-forms/src/tangy-editor-app/tangy-editor-app.js
  develop.sh
  server/index.js
  server/package-lock.json
  server/package.json
  server/reporting/data_processing.js
  server/reporting/generate_csv.js
  server/template.json
Labels: in progress

#870 PR: Add rtl support for tangy-forms
  client/content/default/app-config.json
  client/tangy-forms/src/tangy-form-app/tangy-form-app.js
Labels: in progress

#867 Refactor and Update CSV Generation
  server/reporting/data_processing.js
  server/reporting/generate_csv.js
Labels: review

#880 V3 translations rework
  client/content/default/i18n/translation.json
  client/shell/package.json
  client/shell/src/app/app.component.html
  client/shell/src/app/app.component.ts
  client/shell/src/app/case-management/case-details/case-details.component.html
  client/shell/src/app/case-management/form-list/form-list.component.html
  client/shell/src/app/case-management/observations-by-location/observations-by-location.component.html
  client/shell/src/app/case-management/schools-visited/schools-visited.component.html
  client/shell/src/app/core/auth/login/login.component.html
  client/shell/src/app/core/auth/login/login.component.ts
  client/shell/src/app/core/auth/registration/registration.component.html
  client/shell/src/app/core/auth/registration/registration.component.ts
  client/shell/src/app/core/export-data/export-data/export-data.component.html
  client/shell/src/app/core/export-data/export-data/export-data.component.ts
  client/shell/src/app/core/sync-records/sync-records/sync-records.component.html
  client/shell/src/app/core/update/update/update.component.html
  client/shell/src/app/core/update/update/update.component.ts
  client/shell/src/app/tangy-forms/tangy-forms-player/tangy-forms-player.component.ts
  client/tangy-forms/src/tangy-acasi/tangy-acasi.js
  client/tangy-forms/src/tangy-checkboxes/tangy-checkboxes.js
  client/tangy-forms/src/tangy-editor-app/tangy-editor-app.js
  client/tangy-forms/src/tangy-eftouch/tangy-eftouch.js
  client/tangy-forms/src/tangy-form-app/tangy-form-app.js
  client/tangy-forms/src/tangy-form/cat.js
  client/tangy-forms/src/tangy-form/tangy-form-item.js
  client/tangy-forms/src/tangy-form/tangy-form-redux-middleware.js
  client/tangy-forms/src/tangy-form/tangy-form.js
  client/tangy-forms/src/tangy-gps/tangy-gps.js
  client/tangy-forms/src/tangy-input/tangy-input.js
  client/tangy-forms/src/tangy-location/tangy-location.js
  client/tangy-forms/src/tangy-radio-buttons/tangy-radio-buttons.js
  client/tangy-forms/src/tangy-textarea/tangy-textarea.js
  client/tangy-forms/src/tangy-timed/tangy-timed.js
Labels: in progress

#893 V3 ckeditor plugin fixes
  editor/src/ckeditor/plugins/tangy-checkboxes/plugin.js
  editor/src/ckeditor/plugins/tangy-radio-buttons/plugin.js
Labels: v3.x.x
