Repository Tangerine-Community/Tangerine, pull requests merged in 2018-06, with the labels that each got.

#915 V3 log cleanup
  server/index.js
  server/package.json
Labels: in progress, v3.x.x

#905 Make tangy-form-service.js a TS file
  client/shell/src/app/app.component.ts
  client/shell/src/app/core/auth/_services/user.service.ts
  client/shell/src/app/tangy-forms/tangy-form-service.ts
  client/shell/src/app/user-profile/user-profile.component.ts
Labels: in progress

#872 V2 location list fix
  develop.sh
  docs/debugging_node_apps.md
  ecosystem.json
  reporting/README.md
  reporting/config.js
  reporting/controllers/assessment.js
  reporting/controllers/changes.js
  reporting/controllers/generate_csv.js
  reporting/controllers/result.js
  reporting/controllers/trip.js
  reporting/controllers/workflow.js
  reporting/index.js
  reporting/start.sh
  reporting/utils/dbQuery.js
Labels: review

#923 Set up processing of cache as a batch process
  develop.sh
  entrypoint-development.sh
  server/index.js
  server/reporting/data_processing.js
  server/reporting/run-worker.js
  start.sh
Labels: in progress, v3.x.x

#925 Add batch processing for CSVs that clients can monitor the status of
  Dockerfile
  config.defaults.sh
  develop.sh
  scripts/generate-csv/bin.js
  scripts/generate-csv/generate-lines.js
  scripts/generate-csv/package.json
  server/index.js
  start.sh
Labels: in progress, v3.x.x
